"""Setup.py generated by Quickstart utility"""

# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from codecs import open
from os import path

import os

here = path.abspath(path.dirname(__file__))

with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()

setup(
    name='dixi-tui',
    version='1.0',
    description='Light weight chat client',
    long_description=long_description,
    author='Arden Rasmussen',
    license='MIT',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
    keywords='chat',
    install_requires=["requests"],
    packages=['dixi'],
    entry_points={
        'console_scripts': ['dixi-tui = dixi.dixi:main']
    },)
